package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func runBootstrap(args []string) error {
	root := toolboxRoot()
	if len(args) == 0 {
		return fmt.Errorf("bootstrap: use 'linux-install', 'linux-print', or 'brew-bundle'")
	}
	switch args[0] {
	case "linux-print":
		return bootstrapLinuxPrint(root)
	case "linux-install":
		return bootstrapLinuxInstall(root)
	case "brew-bundle":
		return bootstrapBrewBundle(root, args[1:])
	default:
		return fmt.Errorf("bootstrap: unknown %q", args[0])
	}
}

func bootstrapBrewBundle(root string, args []string) error {
	only := "all"
	pathOnly := false
	for _, a := range args {
		switch {
		case a == "--path-only":
			pathOnly = true
		case strings.HasPrefix(a, "--only="):
			only = strings.TrimPrefix(a, "--only=")
		default:
			return fmt.Errorf("brew-bundle: unknown argument %q (use --only=toolbox|tools|all, --path-only)", a)
		}
	}

	formulas, err := brewFormulas(root, only)
	if err != nil {
		return err
	}
	if len(formulas) == 0 {
		if pathOnly {
			return nil
		}
		fmt.Fprintf(os.Stderr, "brew-bundle: no brew: entries for --only=%s\n", only)
		return nil
	}

	dir, err := os.MkdirTemp("", "toolbox-brew-bundle-*")
	if err != nil {
		return err
	}
	brewfile := filepath.Join(dir, "Brewfile")
	content := buildBrewfile(formulas, only)
	if err := os.WriteFile(brewfile, []byte(content), 0o644); err != nil {
		return err
	}

	if pathOnly {
		fmt.Println(brewfile)
		return nil
	}

	q := shellSingleQuote(brewfile)
	fmt.Fprintf(os.Stderr, "Wrote Homebrew Bundle file (not in the repo; under %s):\n  %s\n\n", dir, brewfile)
	fmt.Fprintf(os.Stderr, "Install missing formulae:\n  brew bundle install --file=%s\n\n", q)
	fmt.Fprintf(os.Stderr, "Check without installing:\n  brew bundle check --file=%s\n", q)
	fmt.Println(brewfile)
	return nil
}

func buildBrewfile(formulas []string, only string) string {
	var b strings.Builder
	b.WriteString("# Generated by: toolbox bootstrap brew-bundle\n")
	b.WriteString("# Temporary file — not committed. Remove the directory after install if you like.\n")
	switch only {
	case "all":
		b.WriteString("# brew: lists from deps/toolbox.yaml + deps/tools.yaml (merged).\n\n")
	case "toolbox":
		b.WriteString("# brew: list from deps/toolbox.yaml\n\n")
	case "tools":
		b.WriteString("# brew: list from deps/tools.yaml\n\n")
	default:
		b.WriteString(fmt.Sprintf("# --only=%s\n\n", only))
	}
	for _, name := range formulas {
		b.WriteString(fmt.Sprintf("brew %q\n", name))
	}
	return b.String()
}

func shellSingleQuote(s string) string {
	return `'` + strings.ReplaceAll(s, `'`, `'\''`) + `'`
}

type linuxPM struct {
	name    string
	binary  string
	install []string // command + flags before package list
}

var linuxPMs = []linuxPM{
	{name: "paru (Arch AUR)", binary: "paru", install: []string{"paru", "-S", "--needed", "--noconfirm"}},
	{name: "pacman (Arch)", binary: "pacman", install: []string{"sudo", "pacman", "-S", "--needed", "--noconfirm"}},
	{name: "apt (Debian/Ubuntu)", binary: "apt", install: []string{"sudo", "apt", "install", "-y"}},
	{name: "dnf (Fedora)", binary: "dnf", install: []string{"sudo", "dnf", "install", "-y"}},
}

func bootstrapLinuxInstall(root string) error {
	var pm *linuxPM
	for i := range linuxPMs {
		if _, err := exec.LookPath(linuxPMs[i].binary); err == nil {
			pm = &linuxPMs[i]
			break
		}
	}

	if pm == nil {
		fmt.Println("bootstrap: no supported package manager found (pacman/apt/dnf); showing install hints instead.")
		fmt.Println()
		return bootstrapLinuxPrint(root)
	}

	// Collect packages from both deps files.
	pkgs, err := linuxPackagesForPM(root, pm.binary)
	if err != nil {
		return err
	}
	if len(pkgs) == 0 {
		fmt.Printf("bootstrap: no packages listed for %s.\n", pm.name)
		return nil
	}

	if pm.binary == "dnf" {
		if err := ensureRPMFusion(); err != nil {
			fmt.Fprintf(os.Stderr, "bootstrap: RPM Fusion setup failed: %v\n", err)
			fmt.Fprintln(os.Stderr, "bootstrap: falling back to manual install hints.")
			fmt.Println()
			return bootstrapLinuxPrint(root)
		}
	}

	fmt.Printf("bootstrap: installing via %s\n", pm.name)
	args := append(pm.install, pkgs...)
	cmd := exec.Command(args[0], args[1:]...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "bootstrap: %s install failed: %v\n", pm.name, err)
		fmt.Fprintln(os.Stderr, "bootstrap: falling back to manual install hints.")
		fmt.Println()
		return bootstrapLinuxPrint(root)
	}
	return nil
}

func ensureRPMFusion() error {
	if err := exec.Command("rpm", "-q", "rpmfusion-free-release").Run(); err == nil {
		return nil // already enabled
	}
	fmt.Println("bootstrap: enabling RPM Fusion repositories...")
	out, err := exec.Command("rpm", "-E", "%fedora").Output()
	if err != nil {
		return fmt.Errorf("could not determine Fedora version: %w", err)
	}
	ver := strings.TrimSpace(string(out))
	freeURL := fmt.Sprintf("https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%s.noarch.rpm", ver)
	nonfreeURL := fmt.Sprintf("https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%s.noarch.rpm", ver)
	cmd := exec.Command("sudo", "dnf", "install", "-y", freeURL, nonfreeURL)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	return cmd.Run()
}

func linuxPackagesForPM(root, binary string) ([]string, error) {
	seen := map[string]struct{}{}
	var pkgs []string
	for _, rel := range []string{"deps/toolbox.yaml", "deps/tools.yaml"} {
		f, err := loadDepsFile(root, rel)
		if err != nil {
			return nil, err
		}
		var list []string
		switch binary {
		case "apt":
			list = f.AptPackages
		case "dnf":
			list = f.DnfPackages
		case "pacman", "paru":
			list = f.PacmanPackages
		}
		for _, p := range list {
			if _, ok := seen[p]; !ok {
				seen[p] = struct{}{}
				pkgs = append(pkgs, p)
			}
		}
	}
	return pkgs, nil
}

func bootstrapLinuxPrint(root string) error {
	printFile := func(title string, rel string) error {
		f, err := loadDepsFile(root, rel)
		if err != nil {
			return err
		}
		if len(f.Brew) == 0 && len(f.AptPackages) == 0 && len(f.DnfPackages) == 0 {
			return nil
		}
		fmt.Printf("## %s (%s)\n", title, rel)
		if len(f.Brew) > 0 {
			fmt.Println("Logical / Homebrew-style names:")
			for _, x := range f.Brew {
				fmt.Printf("  - %s\n", x)
			}
		}
		apt := f.AptPackages
		dnf := f.DnfPackages
		if len(apt) > 0 {
			fmt.Println()
			fmt.Println("# Debian / Ubuntu (paste after sudo apt install -y)")
			fmt.Printf("sudo apt install -y %s\n", joinShellPackages(apt))
		}
		if len(dnf) > 0 {
			fmt.Println()
			fmt.Println("# Fedora (paste after sudo dnf install -y)")
			fmt.Printf("sudo dnf install -y %s\n", joinShellPackages(dnf))
		}
		fmt.Println()
		return nil
	}
	fmt.Println("=== Linux dependency hints (install with your distro; no auto-install) ===")
	fmt.Println()
	if err := printFile("Toolbox prerequisites", "deps/toolbox.yaml"); err != nil {
		return err
	}
	if err := printFile("Optional usual tools", "deps/tools.yaml"); err != nil {
		return err
	}
	fmt.Println(strings.TrimSpace(`
Notes:
  - uv and go must already be on PATH (install via distro or upstream installers).
  - Swift: optional on Linux; Swift tools build only when swiftc exists.
  - Entries without apt_packages/dnf_packages in YAML appear only under logical names; map them manually.
`))
	return nil
}
